name: Unit Test and Analysis with SonarCloud
description: Run unit tests (current node only), can send to SonarCloud
branding:
  icon: check-square
  color: blue

inputs:
  ### Required
  commands:
    description: Commands to run unit tests, start with '|' for multi-line
    required: true

  dir:
    description: App/package directory
    required: true

  ### Typical / recommended
  node_version:
    description: Node version, defaults to 16 (LTS)
    default: "16"

  sonar_args:
    # https://docs.sonarcloud.io/advanced-setup/analysis-parameters/
    description: SonarCloud command line arguments
    default: |
      -Dsonar.organization=bcgov-sonarcloud
      -Dsonar.projectKey=bcgov_${{ github.repository }}

  sonar_comment_token:
    description: Token for pull request comments, usually secrets.GITHUB_TOKEN

  sonar_project_token:
    description: Sonar token, provide unpopulated token for pre-setup (will skip)

  triggers:
    description: Paths used to trigger a build; e.g. ('./backend/' './frontend/)

  ### Usually a bad idea / not recommended
  repository:
    description: Non-default repository to clone
    default: ${{ github.repository }}

runs:
  using: composite
  steps:
    # Shallow clone is faster, but SonarCloud requires a full clone
    - uses: actions/checkout@v3
      if: (! inputs.sonar_project_token)
      with:
        repository: ${{ inputs.repository }}

    # Shallow clone is faster, but can't be used with SonarCloud
    - uses: actions/checkout@v3
      if: inputs.sonar_project_token
      with:
        # Disable shallow clone for SonarCloud analysis
        fetch-depth: 0
        repository: ${{ inputs.repository }}

    # Process variables and inputs
    - id: vars
      shell: bash
      run: |
        # Expand for inputs and variables

        # Triggers
        TRIGGERS=${{ inputs.triggers }}
        if [ -z "${TRIGGERS}" ]; then
          echo "Triggers omitted, so always test"
          echo "triggered=true" >> $GITHUB_OUTPUT
          exit 0
        else
          echo "Processing triggers"
          git fetch origin "${{ inputs.diff_branch }}"
          while read -r check; do
            for t in "${TRIGGERS[@]}"; do
              if [[ "${check}" =~ "${t}" ]]; then
                  echo -e "Triggered: ${t}\n --> ${check}"
                  echo "triggered=true" >> $GITHUB_OUTPUT
                  exit 0
              fi
            done
          done < <(git diff origin/"${{ inputs.diff_branch }}" --name-only)
        fi
        echo "Triggers not matched, testing skipped"
        echo "triggered=true" >> $GITHUB_OUTPUT

    # Exit successfully if provided triggers did not fire
    - name: Exit early
      if: steps.vars.outputs.triggered == false
      shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}

    # Setup node and cache dir
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
    - id: npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v3
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-

    # Run tests, hopefully generating coverage for SonarCloud
    - name: Run Tests
      shell: bash
      run: |
        cd ${{ inputs.dir }}
        ${{ inputs.commands }}

    ### Optional SonarCloud

    # If sonar_project_token and sonar_comment_token, then run with comments
    - name: SonarCloud Scan
      if: inputs.sonar_project_token && inputs.sonar_comment_token
      uses: SonarSource/sonarcloud-github-action@v2.0.0
      env:
        GITHUB_TOKEN: ${{ inputs.sonar_comment_token }}
        SONAR_TOKEN: ${{ inputs.sonar_project_token }}
      with:
        projectBaseDir: ${{ inputs.dir }}
        args: >
          -Dsonar.pullrequest.github.summary_comment=true
          ${{ inputs.sonar_args }}

    # If sonar_project_token and not sonar_comment_token, then run without comments
    - name: SonarCloud Scan
      if: inputs.sonar_project_token && ! inputs.sonar_comment_token
      uses: SonarSource/sonarcloud-github-action@v2.0.0
      env:
        SONAR_TOKEN: ${{ inputs.sonar_project_token }}
      with:
        projectBaseDir: ${{ inputs.dir }}
        args: >
          -Dsonar.pullrequest.github.summary_comment=false
          ${{ inputs.sonar_args }}

    ### Cleanup

    # Fix - Docker takes ownership of files, causing a cleanup fail
    - shell: bash
      id: get_uid
      run: |
        # User for workstation ownership reset/fix
        echo "uid=$(id -u ${USER})" >> $GITHUB_OUTPUT
    - uses: peter-murray/reset-workspace-ownership-action@v1
      with:
        user_id: ${{ steps.get_uid.outputs.uid }}

    # Fix - Clone for action.yml and other verifications
    - name: Checkout Action repo to pass tests
      uses: actions/checkout@v3
