name: Unit Test and Analysis with SonarCloud
description: Run unit tests (current node only), can send to SonarCloud
branding:
  icon: check-square
  color: blue

inputs:
  ### Required
  commands:
    description: Commands to run unit tests, start with '|' for multi-line
    required: true
  dir:
    description: App/package directory
    required: true

  ### Typical / recommended
  node_version:
    description: Node version, defaults to 16 (LTS)
    default: "16"
  sonar_args:
    # https://docs.sonarcloud.io/advanced-setup/analysis-parameters/
    description: SonarCloud command line arguments
    default: |
      -Dsonar.organization=bcgov-sonarcloud
      -Dsonar.projectKey=bcgov_${{ github.repository }}
  sonar_project_token:
    description: Sonar token, provide unpopulated token for pre-setup (will skip)

  ### Usually a bad idea / not recommended
  repository:
    description: Non-default repository to clone, defaults to calling/current repository
    default: ${{ github.repository }}
  repoClone:
    description: Clone or not, defaults to true (yes, do clone)
    default: "true"

runs:
  using: composite
  steps:
    # Process inputs
    - id: inputs
      shell: bash
      run: |
        # Process inputs
        if [ -z ${{ inputs.sonar_project_token }} ]; then
          shallowClone=1 >> $GITHUB_OUTPUT
        fi

        TRUES=(true yes 1)
        if [ ${{ inputs.repoClone }} =~ ${TRUES} ]; then
          repoClone="true" >> $GITHUB_OUTPUT
        fi

    # SonarCloud uses shallow clone (fetch-depth=0), which is a bit slower/heavier
    - uses: actions/checkout@v3
      if: steps.inputs.outputs.repoClone
      with:
        fetch-depth: steps.inputs.outputs.shallowClone
        repository: ${{ inputs.repository }}

    # Setup node and cache dir
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
    - id: npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v3
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-

    # Run tests, hopefully generating coverage for SonarCloud
    - shell: bash
      run: |
        # Run tests
        cd ${{ inputs.dir }}
        ${{ inputs.commands }}

    ### Optional SonarCloud

    # If sonar_project_token, then run with comments
    - if: inputs.sonar_project_token
      uses: SonarSource/sonarcloud-github-action@v1.8
      env:
        SONAR_TOKEN: ${{ inputs.sonar_project_token }}
      with:
        projectBaseDir: ${{ inputs.dir }}
        args: ${{ inputs.sonar_args }}

    # Fix - Docker takes ownership of files, causing a cleanup fail
    - shell: bash
      id: get_uid
      run: |
        actions_user_id=`id -u $USER`
        echo $actions_user_id
        echo "uid=${actions_user_id}" >> $GITHUB_OUTPUT
    - uses: peter-murray/reset-workspace-ownership-action@v1
      with:
        user_id: ${{ steps.get_uid.outputs.uid }}

    # Fix - Clone for action.yml and other verifications
    - name: Checkout Action repo to pass tests
      uses: actions/checkout@v3
