name: Unit Test and Analysis with SonarCloud
description: Run unit tests (current node only), can send to SonarCloud
branding:
  icon: check-square
  color: blue

inputs:
  ### Required
  commands:
    description: Commands to run unit tests, start with '|' for multi-line
    required: true

  dir:
    description: App/package directory
    required: true

  node_version:
    description: Node version to use
    required: true

  ### Typical / recommended
  sonar_args:
    # https://docs.sonarcloud.io/advanced-setup/analysis-parameters/
    description: SonarCloud command line arguments
    default: |
      -Dsonar.organization=bcgov-sonarcloud
      -Dsonar.projectKey=bcgov_${{ github.repository }}

  sonar_token:
    description: Sonar token, provide unpopulated token for pre-setup (will skip)

  triggers:
    description: Paths used to trigger a build; e.g. ('./backend/' './frontend/)

  ### Usually a bad idea / not recommended
  diff_branch:
    description: Branch to diff against
    default: ${{ github.event.repository.default_branch }}

  repository:
    description: Non-default repository to clone (used for testing this action)
    default: ${{ github.repository }}
  
  branch:
    description: Non-default branch to clone (used for testing this action)
    default: ""

  triggers_limited:
    description: Limit triggers to PRs; always fire on merge, cronjob, dispatch, etc.
    default: true

runs:
  using: composite
  steps:
    # Shallow clone is faster, but SonarCloud requires a full clone
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.branch }}
    
    - name: Warnings for breaking changes
      shell: bash
      run: |
        # Warnings for breaking changes

        # node_version now required
        if [ -z "${{ inputs.node_version }}" ]; then
          echo -e "\nnode_version now required.  Previous default: 16."
          echo -e "\n\tAction: add a node_version parameter\n"
          exit 1
        fi

        # sonar_project_token renamed sonar_token
        if [ ! -z "${{ inputs.sonar_project_token }}" ]; then
          echo -e "\nsonar_project_token renamed.  Please correct this and try again."
          echo -e "\n\tAction: rename sonar_project_token to sonar_token\n"
          exit 1
        fi

        #
        if [ ! -z "${{ inputs.sonar_comment_token }}" ]; then
          echo -e "\nsonar_comment_token deprecated.  Please correct this and try again."
          echo -e "\n\tAction: remove sonar_comment_token parameter\n"
          exit 1
        fi

    # Process variables and inputs
    - id: vars
      shell: bash
      run: |
        # Expand for inputs and variables

        # Triggers
        TRIGGERS=${{ inputs.triggers }}
        echo "triggered=true" >> $GITHUB_OUTPUT
        if "${{ github.event_name != 'pull_request' }}" && "${{ inputs.triggers_limited }}"; then
          echo "Not a pull request, so always test"
          exit 0
        elif [ -z "${TRIGGERS}" ]; then
          echo "Triggers omitted, so always test"
          exit 0
        else
          echo "Processing triggers"
          git fetch origin "${{ inputs.diff_branch }}"
          while read -r check; do
            for t in "${TRIGGERS[@]}"; do
              if [[ "${check}" =~ "${t}" ]]; then
                  echo -e "Triggered: ${t}\n --> ${check}"
                  exit 0
              fi
            done
          done < <(git diff origin/"${{ inputs.diff_branch }}" --name-only)
        fi
        echo "Triggers not matched, testing skipped"
        echo "triggered=false" >> $GITHUB_OUTPUT

    # Setup node and cache dir
    - uses: actions/setup-node@v3
      if: steps.vars.outputs.triggered == 'true'
      with:
        node-version: ${{ inputs.node_version }}
    - id: npm-cache-dir
      if: steps.vars.outputs.triggered == 'true'
      shell: bash
      run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v3
      if: steps.vars.outputs.triggered == 'true'
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-

    # Run tests, hopefully generating coverage for SonarCloud
    - name: Run Tests
      if: steps.vars.outputs.triggered == 'true'
      shell: bash
      run: |
        cd ${{ inputs.dir }}
        ${{ inputs.commands }}

    ### Optional SonarCloud

    # If sonar_token
    - name: SonarCloud Scan
      if: inputs.sonar_token && steps.vars.outputs.triggered == 'true'
      uses: SonarSource/sonarcloud-github-action@v2.0.0
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
      with:
        projectBaseDir: ${{ inputs.dir }}
        args: >
          ${{ inputs.sonar_args }}

    ### Cleanup

    # Fix - Docker takes ownership of files, causing a cleanup fail
    - shell: bash
      if: steps.vars.outputs.triggered == 'true'
      id: get_uid
      run: |
        # User for workstation ownership reset/fix
        echo "uid=$(id -u ${USER})" >> $GITHUB_OUTPUT
    - uses: peter-murray/reset-workspace-ownership-action@v1
      if: steps.vars.outputs.triggered == 'true'
      with:
        user_id: ${{ steps.get_uid.outputs.uid }}

    # Fix - Clone for action.yml and other verifications
    - name: Checkout Action repo to pass tests
      if: inputs.repository != github.repository
      uses: actions/checkout@v3
